= Changelog

== Version 0.9.0

Date: unreleased

Important notes:

- The `bcrypt+sha384` algorithm is becomes the new default password hasher.
  The previous `bcrypt+sha512` is still available but is deprecated because
  of hash truncation. It does not has security implications because the
  standard way to use bcrypt is combining with 256 bit hash and the impl in
  buddy was ussing 512 bit hash truncated to 256bits. The new implementation
  does not uses any explicit hash truncation.
  Among that, is still recommeded upgrade your passwords to the new hash
  algorithm using the provided way to gradual password upgrading.
- Fixed wrong output digest size in `pbkdf2+sha256`.
  This is a breaking change, so if you are using this hasher you should update
  your database replacing the `pbkdf2+sha256$` prefix on the password field with
  `pbkdf2+sha256b$` if you want continue validating properly that passwords.
  The security implications of this bug is that the old implementation of
  `pbkdf2+sha256` has truncation of digest size to 160 bits, and it means that
  the security is decreased to be at least as in `pbkdf2+sha1`. The last one
  is still considered secure and is continued to be widelly used.

Other changes:

- The `pbkdf2+sha3_256` is renamed to `pbkdf2+sha3-256`. This is a backward
  compatible change because the previous alias is still conserved.
- The `md5` and `sha256` hashers has been deprecated and will be removed in the
  next version.
- The `:algorithm` parameter is deprecated in favor of the shorter `:alg`.


== Version 0.8.0

Date: 2015-10-31

- Add the ability to limit the set of allowed algorithms
  to be used in the check process.
- Add the ability to react in case the password has weak
  configuration and rehash it again (and store fresh
  encoded password with updated stronger config).
- Decrease the rounds for :pbkdf2-sha3_256 because
  the previous one was too heavy.


== Version 0.7.0

Date: 2015-09-19

- Set default clojure version to 1.7.0
- Update buddy-core version to 0.7.0


== Version 0.6.0

Date: 2015-06-28

- Update to buddy-core 0.6.0
- Remove buddy-hashers 0.2.x hashers implementation.


== Version 0.5.0

Date: 2015-06-15

- `check` function is now null pointer safe.


== Version 0.4.2

Date: 2015-04-03

- Update buddy-core to 0.5.0


== Version 0.4.1

Date: 2015-03-14

- Update buddy-core from 0.4.0 to 0.4.2


== Version 0.4.0

Date: 2015-02-22

- Update buddy-core dependency version to 0.4.0
- Adapt the code to buddy-core 0.4.0


== Version 0.3.0

Date: 2015-01-18

- First version splitted from monolitic buddy package.
- Add complete refactored version of hashers, more flexible and extensible.
- Add support for pbkdf2+sha256 and pbkdf2+sha3_256 password hasher algorithms.
- Maintain the old namespace for backward compatibility.