= buddy-hashers - password hashers for Clojure
Andrey Antukh, <niwi@niwi.nz>
0.6.0
:toc: left
:!numbered:
:source-highlighter: pygments
:pygments-style: friendly
:sectlinks:
:idseparator: -
:idprefix:
:toclevels: 2

== Introduction

Buddy *hashers* module is dedicated to provide a collection
of secure password hashers functions.

.Supported password hashers algorithms
[options="header", cols="^1,^1,^3"]
|===========================================================================
| Identifier         | Should I use it? | Description
| `:bcrypt+sha512`   | Recommended      |BCrypt password hasher combined with sha512 (due to 75 chars password limitation of bcrypt)
| `:pbkdf2+sha256`   | Recommended      | Password-Based Key Derivation Function 2 with SHA256
| `:pbkdf2+sha3_256` | Yes              | Password-Based Key Derivation Function 2 with SHA3 256bit
| `:pbkdf2+sha1`     | Yes              | Password-Based Key Derivation Function 2 (as defined in RFC2898)
| `:scrypt`          | Yes              | Password-Based Key Derivation Function created by Colin Percival
| `:sha256`          | No               | Simple hash based password hasher that uses sha256.
| `:md5`             | No               | Simple hash based password hasher that uses md5.
|===========================================================================

== Project Maturity

Since _buddy-hashers_ is a young project there can be some API breakage.


== Install

This section covers the _buddy-hashers_ library installing process and its requirements.


=== Requirements

_buddy-hashers_ is tested with these platforms:

- JDK7
- JDK8


=== Leiningen

The simplest way to use _buddy-hashers_ in a clojure project, is by including it in the dependency
vector on your *_project.clj_* file:

._on project.clj_
[source,clojure]
----
[buddy/buddy-hashers "0.6.0"]
----

=== Gradle

If you are using gradle, this is a dependency line for gradle dsl:

[source,groovy]
----
compile "buddy:buddy-hashers:0.6.0"
----


== Quick Start

Hashers module consists in two public functions: *encrypt* and *check* and both them are
located on `buddy.hashers` namespace.

For start using it, just import it on your namespace:

[source,clojure]
----
(ns my.app
  (:require [buddy.hashers :as hashers]))
----

Now, choice the algorithm and encrypt your passwords:

[source,clojure]
----
;; Generate hash from plain password
(hashers/encrypt "secretpassword"))
;; => "bcrypt+sha512$4i9sd34m..."

(hashers/check "secretpassword" "bcrypt+sha512$4i9sd34m..."))
;; => true
----

The `:bcrypt+sha512` is a default algorithm, but if you want other, you can
specify it using the the second parameter to *encrypt* function:

[source,clojure]
----
;; Generate hash from plain password
(hashers/encrypt "secretpassword" {:algorithm :pbkdf2+sha256))
;; => "pbkdf2+sha256$4i9sd34m..."

(hashers/check "secretpassword" "pbkdf2+sha256$4i9sd34m..."))
;; => true
----

NOTE: hasher functions, unlike cryptographic hash functions, expect strings instead
of bytes.

== Advanced options

Each algorithm can be tweaked passing additional parameters on the second argument
to *encrypt* function. And options vary depending on the used algorithm.

.Table that deails available options and their defaults
[options="header", cols="^1,^3,^4"]
|==========================================================
| Algorithm | Available options | Defaults
| `:bcrypt+sha512` | `:salt`, `:iterations` | iterations=12, salt=random
| `:pbkdf2+sha256` | `:salt`, `:iterations` | iterations=100000, salt=random
| `:pbkdf2+sha3_256` | `:salt`, `:iterations` | iterations=100000, salt=random
| `:pbkdf2+sha1` | `:salt`, `:iterations` | iterations=100000, salt=random
| `:scrypt` | `:salt`, `:cpucost`, `:memcost`, `:parallelism` | salt=random, cpucost=65536, memcost=8, parallelism=1
| `:sha256` | `:salt` | salt=random
| `:md5` | `:salt` | salt=random
|==========================================================


== Developers Guide

=== Contributing

Unlike Clojure and other Clojure contributed libraries _buddy-hashers_ does not have many
restrictions for contributions. Just open an issue or pull request.


=== Philosophy

Five most important rules:

- Beautiful is better than ugly.
- Explicit is better than implicit.
- Simple is better than complex.
- Complex is better than complicated.
- Readability counts.

All contributions to _buddy-hashers_ should keep these important rules in mind.


=== Get the Code

_buddy-hashers_ is open source and can be found on link:https://github.com/funcool/buddy-hashers[github].

You can clone the public repository with this command:

[source,text]
----
git clone https://github.com/funcool/buddy-hashers
----


=== Run tests

For running tests just execute this:

[source,bash]
----
lein test
----


=== License

_buddy-hashers_ is licensed under Apache 2.0 License. You can see the complete text
of the license on the root of the repository on `LICENSE` file.
