= buddy-hashers - password hashers for Clojure
Andrey Antukh, <niwi@niwi.nz>
1.4.0
:toc: left
:!numbered:
:source-highlighter: pygments
:pygments-style: friendly
:sectlinks:
:idseparator: -
:idprefix:
:toclevels: 2

== Introduction

*buddy-hashers* provides a collection of secure password hashers
with lightweight and extensible abstraction for building powerful
password authentication processes.

.Supported password hashers algorithms
[options="header", cols="1,1,3"]
|===========================================================================
| Identifier         | Can I use it? | Description
| `:bcrypt+blake2b-512` | Recommended | BCrypt password hasher combined with blake2b-512
| `:pbkdf2+blake2b-512` | Recommended | Password-Based Key Derivation Function 2 with blake2b-512
| `:pbkdf2+sha512`   | Recommended | Password-Based Key Derivation Function 2 with SHA256
| `:pbkdf2+sha3-256` | Recommended | Password-Based Key Derivation Function 2 with SHA3-256
| `:bcrypt+sha512`   | Recommended | BCrypt password hasher combined with sha512 (default).
| `:pbkdf2+sha256`   | Yes | Password-Based Key Derivation Function 2 with SHA256
| `:bcrypt+sha384`   | Yes | BCrypt password hasher combined with sha384
| `:pbkdf2+sha1`     | Yes | Password-Based Key Derivation Function 2 (as defined in RFC2898)
| `:scrypt`          | Yes | Password-Based Key Derivation Function created by Colin Percival
|===========================================================================


=== Project Maturity

Since _buddy-hashers_ is a young project there can be some API breakage.


=== Installation

The simplest way to use _buddy-core_ in a Clojure project is by including it in
the `:dependencies` vector in your *_project.clj_* file:

[source,clojure]
----
[buddy/buddy-hashers "1.4.0"]
----

This has been tested with JDK 8.


[[quickstart]]
== Quick Start

The `hashers` namespace consists of two public functions: *derive* and *check*.
Both of these are located in the `buddy.hashers` namespace.

Let's start by deriving a password:

[source,clojure]
----
(require '[buddy.hashers :as hashers])

;; Generate hash from plain password
(hashers/derive "secretpassword")
;; => "bcrypt+sha512$4i9sd34m..."

(hashers/check "secretpassword" "bcrypt+sha512$4i9sd34m...")
;; => true
----

If no algorithm is specified, `:bcrypt+sha512` will be used.
If you want to use a specific algorithm, you can specify it using the optional
`options` parameter:

[source,clojure]
----
;; Generate hash from plain password
(hashers/derive "secretpassword" {:alg :pbkdf2+sha256})
;; => "pbkdf2+sha256$4i9sd34m..."

;; Verify the password against the hash
(hashers/check "secretpassword" "pbkdf2+sha256$4i9sd34m...")
;; => true
----

== Advanced Options

=== Algorithm Tuning Parameters

Each algorithm can be tweaked by passing additional parameters in the second
argument to *derive*. Which options are valid depends on the algorithm in use.

.Table of available options and their defaults
[options="header", cols="2,2,4"]
|==========================================================
| Algorithm | Available options | Defaults
| `:bcrypt+blake2b-512` | `:salt`, `:iterations` | iterations=12, salt=(random 16 bytes)
| `:bcrypt+sha384` | `:salt`, `:iterations` | iterations=12, salt=(random 16 bytes)
| `:pbkdf2+blake2b-512` | `:salt`, `:iterations` | iterations=50000, salt=(random 12 bytes)
| `:pbkdf2+sha512` | `:salt`, `:iterations` | iterations=100000, salt=(random 12 bytes)
| `:pbkdf2+sha3_256` | `:salt`, `:iterations` | iterations=100000, salt=(random 12 bytes)
| `:pbkdf2+sha1` | `:salt`, `:iterations` | iterations=100000, salt=(random 12 bytes)
| `:scrypt` | `:salt`, `:cpucost`, `:memcost`, `:parallelism` | salt=(random 12 bytes), cpucost=65536, memcost=8, parallelism=1
| `:bcrypt+sha512` | `:salt`, `:iterations` | iterations=12, salt=(random 12 bytes)
| `:pbkdf2+sha256` | `:salt`, `:iterations` | iterations=100000, salt=(random 12 bytes)
|==========================================================


=== Limiting Algorithms

Sometimes you want to limit the set of algorithms used. This can be accomplished
by passing additional parameter to the `check` function:

[source, clojure]
----
(def trusted-algs #{:pbkdf2+sha256 :bcrypt+sha512})

(hashers/check incoming-pwd derived-pwd {:limit trusted-algs})
----

The *check* function returns `false` if the given password uses an algorithm
that is not allowed.


=== Rehash Hook

Choosing a strong hashing algorithm is important, but having a policy for
updating password hashes is also very important and often completely forgotten.
A password generated 3 years ago is often weaker than one generated today...

*buddy-hashers* comes with a solution for making this task easier. It consists of
a setter hook that will be called when weaker password is detected, enabling you
to rehash the password and store the new hash.

Here's an example of how it may be used:

[source, clojure]
----
(letfn [(setter [pwd]
          (let [pwd (hashers/derive pwd)]
            (do-the-db-update pwd)))]
  (hashers/check incoming-pwd derived-pwd {:setter setter}))
----

The setter will be called when the incoming password is valid but its config
is weaker that the current default one.


== Developer Guide

=== Philosophy

Five most important rules:

- Beautiful is better than ugly.
- Explicit is better than implicit.
- Simple is better than complex.
- Complex is better than complicated.
- Readability counts.

All contributions to _buddy-hashers_ should keep these important rules in mind.


=== Contributing

Unlike Clojure and other Clojure contributed libraries _buddy-hashers_ does not
have many restrictions for contributions. Just open an issue or pull request.


=== Get the Code

_buddy-hashers_ is open source and can be found on
link:https://github.com/funcool/buddy-hashers[github].

You can clone the public repository with this command:

[source,text]
----
git clone https://github.com/funcool/buddy-hashers
----


=== Running tests

To run the tests, just execute this:

[source,bash]
----
lein test
----


=== License

_buddy-hashers_ is licensed under the Apache 2.0 License. The complete license text
is a available in the `LICENSE` file in the repository root.
