= buddy-hashers - password hashers for Clojure
Andrey Antukh, <niwi@niwi.nz>
0.8.0
:toc: left
:!numbered:
:source-highlighter: pygments
:pygments-style: friendly
:sectlinks:
:idseparator: -
:idprefix:
:toclevels: 2

== Introduction

*buddy-hashers* provides a collection of secure password hashers
with lightweight and extensible abstraction for build powerfull
password authentication processes.

.Supported password hashers algorithms
[options="header", cols="1,1,3"]
|===========================================================================
| Identifier         | Can I use it? | Description
| `:bcrypt+sha386`   | Recommended      |BCrypt password hasher combined with sha512 (due to 75 chars password limitation of bcrypt)
| `:pbkdf2+blake2b-512`   | Recommended      | Password-Based Key Derivation Function 2 with Blake2b-512
| `:pbkdf2+sha256`   | Recommended      | Password-Based Key Derivation Function 2 with SHA256
| `:pbkdf2+sha3_256` | Yes              | Password-Based Key Derivation Function 2 with SHA3 256bit
| `:pbkdf2+sha1`     | Yes              | Password-Based Key Derivation Function 2 (as defined in RFC2898)
| `:scrypt`          | Yes              | Password-Based Key Derivation Function created by Colin Percival
| `:bcrypt+sha512`   | No               | BCrypt password hasher combined with sha512 (see release notes for more information about that).
|===========================================================================


=== Project Maturity

Since _buddy-hashers_ is a young project there can be some API breakage.


=== Install

This section covers the _buddy-hashers_ library installing process and its requirements.


==== Requirements

_buddy-hashers_ is tested with these platforms:

- JDK7
- JDK8


=== Leiningen

The simplest way to use _buddy-hashers_ in a clojure project, is by including it in
the dependency list on your *_project.clj_* file:

[source,clojure]
----
[buddy/buddy-hashers "0.8.0"]
----

[[quickstart]]
== Quick Start

Hashers module consists in two public functions: *encrypt* and *check* and both
them are located on `buddy.hashers` namespace.

Let start encrypting a password:

[source,clojure]
----
(require '[buddy.hashers :as hashers])

;; Generate hash from plain password
(hashers/encrypt "secretpassword"))
;; => "bcrypt+sha512$4i9sd34m..."

(hashers/check "secretpassword" "bcrypt+sha512$4i9sd34m..."))
;; => true
----

The `:bcrypt+sha512` is a default algorithm, but if you want other, you can
specify it using the the second parameter to *encrypt* function:

[source,clojure]
----
;; Generate hash from plain password
(hashers/encrypt "secretpassword" {:algorithm :pbkdf2+sha256))
;; => "pbkdf2+sha256$4i9sd34m..."

(hashers/check "secretpassword" "pbkdf2+sha256$4i9sd34m..."))
;; => true
----

== Advanced options

=== Algorithm tunning params

Each algorithm can be tweaked passing additional parameters on the second argument
to *encrypt* function. And options vary depending on the used algorithm.

.Table that deails available options and their defaults
[options="header", cols="^1,^3,^4"]
|==========================================================
| Algorithm | Available options | Defaults
| `:bcrypt+sha512` | `:salt`, `:iterations` | iterations=12, salt=random
| `:pbkdf2+sha256` | `:salt`, `:iterations` | iterations=100000, salt=random
| `:pbkdf2+sha3_256` | `:salt`, `:iterations` | iterations=100000, salt=random
| `:pbkdf2+sha1` | `:salt`, `:iterations` | iterations=100000, salt=random
| `:scrypt` | `:salt`, `:cpucost`, `:memcost`, `:parallelism` | salt=random, cpucost=65536, memcost=8, parallelism=1
| `:sha256` | `:salt` | salt=random
| `:md5` | `:salt` | salt=random
|==========================================================

=== Limiting algorithms

Some times you don't want to use all the supported algorithms and you only want
to use a own set of algorithms in the password check process. That can be done
passing additional parameter to the `check` function:

[source, clojure]
----
(def trusted-algs #{:pbkdf2+sha256 :bcrypt+sha512})

(hashers/check incoming-pwd encrypted-pwd {:limit trusted-algs})
----

The `check` function will return false if the incoming password uses an algorithm
that does not allowed.


=== Rehash Hook


Choice a strong algorithm is important thing, but have a good update
password-hashes policy is also very important and usually completelly forgotten.
The password generated 3 years ago is weaker that one generated today...

*buddy-hashers* comes with a solution for make this task easier. It consists in
a setter hook that will be called when weaker password is detected, enabling for
you the entry point for rehash the password and store it again to the database.

It there is an example on how it can be used:

[source, clojure]
----
(letfn [(setter [pwd]
          (let [pwd (hashers/encrypt pwd)]
            (do-the-db-update pwd)))]
  (hashers/check incoming-pwd encrypted-pwd {:setter setter}))
----

The setter will be called when the incoming password is valid but its config
is weaker that the current default one.


== Developers Guide

=== Philosophy

Five most important rules:

- Beautiful is better than ugly.
- Explicit is better than implicit.
- Simple is better than complex.
- Complex is better than complicated.
- Readability counts.

All contributions to _buddy-hashers_ should keep these important rules in mind.


=== Contributing

Unlike Clojure and other Clojure contributed libraries _buddy-hashers_ does not
have many restrictions for contributions. Just open an issue or pull request.


=== Get the Code

_buddy-hashers_ is open source and can be found on
link:https://github.com/funcool/buddy-hashers[github].

You can clone the public repository with this command:

[source,text]
----
git clone https://github.com/funcool/buddy-hashers
----


=== Run tests

For running tests just execute this:

[source,bash]
----
lein test
----


=== License

_buddy-hashers_ is licensed under Apache 2.0 License. You can see the complete text
of the license on the root of the repository on `LICENSE` file.
